---
# Since Atlassian does NOT provide either preseed config options or an API,
# we will have to do this the hard way.

# TODO better security: have jvm only listen on localhost
# TODO How can we check if Setup has finished? if table exists?

- name: "Choose External Database: PostgreSQL"
  uri: url=http://localhost:8090/setup/setupdbchoice.action
    method=POST
    body="dbChoiceSelect=postgresql&standard=External+Database"
    HEADER_Content-Type="application/x-www-form-urlencoded"
    status_code=302
    timeout=3600
  register: wizard

- name: "Configure Database: Direct JDBC"
  uri: url=http://localhost:8090/setup/setupdb.action
    method=POST
    body="selectedDatabaseType=database-type-standard&database=postgresql"
    HEADER_Content-Type="application/x-www-form-urlencoded"
    HEADER_Cookie="{{ wizard.set_cookie }}"
    status_code=302
    timeout=3600
    
- name: "Setup Database (takes a while...)"
  uri: url=http://localhost:8090/setup/setupstandarddb.action
    method=POST
    body="dbConfigInfo.driverClassName=org.postgresql.Driver&dbConfigInfo.databaseUrl=jdbc%3Apostgresql%3A%2F%2F{{ atlassian_confluence_db_host | urlencode }}%3A5432%2F{{ atlassian_confluence_db_name | urlencode }}&dbConfigInfo.userName={{ atlassian_confluence_db_username | urlencode }}&dbConfigInfo.password={{ atlassian_confluence_db_password | urlencode }}&database=postgresql&setup-next-button=Next"
    HEADER_Content-Type="application/x-www-form-urlencoded"
    HEADER_Cookie="{{ wizard.set_cookie }}"
    status_code=302
    timeout=3600


# Without this hidden step you will receive a 500 error near the end:
# 'No remote JIRA directory found. Should have already been created in the previous step'
- name: "Set up paths"
  uri: url=http://localhost:8090/setup/setuppaths.action
    method=GET
    HEADER_Cookie="{{ wizard.set_cookie }}"
    status_code=200
    follow_redirects=all
    timeout=3600

- name: "Load Content: Empty Site"
  uri: url=http://localhost:8090/setup/setupdata.action
    method=POST
    body="dbchoiceSelect=Empty+Site&contentChoice=blank"
    HEADER_Content-Type="application/x-www-form-urlencoded"
    HEADER_Cookie="{{ wizard.set_cookie }}"
    status_code=302
    timeout=3600


- name: "Configure User Management"
  uri: url=http://localhost:8090/setup/setupusermanagementchoice.action
    method=POST
    body='userManagementChoice=internal&internal=Manage+users+and+groups+within+Confluence'
    HEADER_Content-Type="application/x-www-form-urlencoded"
    HEADER_Cookie="{{ wizard.set_cookie }}"
    status_code=302
    timeout=3600


- name: "Manage users and groups"
  uri: url=http://localhost:8090/setup/setupadministrator.action
    method=POST
    body="username={{ atlassian_confluence_admin_username | urlencode }}&fullName={{ atlassian_confluence_admin_fullname | urlencode }}&email={{ atlassian_confluence_admin_email | urlencode }}&password={{ atlassian_confluence_admin_password | urlencode }}&confirm={{ atlassian_confluence_admin_password | urlencode }}&setup-next-button=Next"
    HEADER_Content-Type="application/x-www-form-urlencoded"
    HEADER_Cookie="{{ wizard.set_cookie }}"
    status_code=302
    timeout=3600


- name: "Finisher"
  uri: url=http://localhost:8090/finishsetup.action
    method=GET
    HEADER_Content-Type="application/x-www-form-urlencoded"
    HEADER_Cookie="{{ wizard.set_cookie }}"
    status_code=200
    timeout=3600
